---
name: Feature Branch Push Workflow

on:
  push:
    branches-ignore:
      - main

jobs:
  validate:
    uses: eingram-homelab/reusable_workflows/.github/workflows/_packer-validate.yaml@main
    name: Validate Packer Project
    secrets:
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}

  gate:
    if: ${{ always() }}
    needs: validate
    runs-on: arc-runners
    steps:
      - name: Always succeed
        run: exit 0
