name: Release Workflow

on:
  push:
    branches: [ main ]
    paths:
      - '**.pkr.hcl'

jobs:
  validate:
    uses: eingram-homelab/reusable_workflows/.github/workflows/_packer-build.yaml@main
    name: Build vSphere Template
    secrets:
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}